const test = require('tape')
const print = console.log.bind(console)
const tapDiff = require('tap-diff')
const {HyperScript} = require('../lib/index')


if(!module.parent) {
  test.createStream()
    .pipe(tapDiff())
    .pipe(process.stdout);
}

let fix = {
  props: {
    class: ['foo', 'bar'],
    className: ['bar', 'baz'],
    style: {
      position: 'absolute',
      backgroundColor: '#ff0000',
    },
    title: 'A title attribute',
  }
}

function Results() {
  let ret = []
  Object.defineProperty(ret, 'last', { get: function(v) { return this[this.length - 1] } })
  return Object.defineProperty(ret, 'more', { set: function(v) { this.push(v) } })
}


test(`hyperscript should return a single tag when supplied with no \
  args, null args, or empty args.`, function (t) {
  let h = HyperScript()
  let r = Results(), results = r
  let expect =
`<p>
</p>`

  t.comment(expect)
  r.more = h('p')
  r.more = h('p', null, null)
  r.more = h('p', {}, [])

  for (let r of results)
    t.equal(r, expect)

  t.end()
})

test(`hyperscript should return a single tag with attrs, when supplied \
a properties object.`, function (t) {
  let h = HyperScript()
  let expect =
`<p
 class="foo bar bar baz"
 style="position:absolute; backgroundColor:#ff0000"
 title="A title attribute">
</p>`

  t.comment(expect)
  let result = h('p', fix.props)

  t.equal(result, expect)

  t.end()
})

test(`hyperscript should produce the same html with the same children \
arranged in various arrays at various depths, in the same order, \
with or without a null options arg.`, function (t) {
  let h = HyperScript()
  let r = Results(), results = r
  let expect =
`<div>
\tText A.
\tText B.
\tText C.
\tText D.
</div>`

  t.comment(expect)
  r.more = h('div', null, 'Text A.', 'Text B.', 'Text C.', 'Text D.')
  r.more = h('div', 'Text A.', 'Text B.', 'Text C.', 'Text D.')
  r.more = h('div', null, ['Text A.', 'Text B.', 'Text C.', 'Text D.'])
  r.more = h('div', ['Text A.', 'Text B.', 'Text C.', 'Text D.'])
  r.more = h('div', null, 'Text A.', ['Text B.', 'Text C.'], 'Text D.')
  r.more = h('div', 'Text A.', ['Text B.', 'Text C.'], 'Text D.')
  r.more = h('div', null, ['Text A.', ['Text B.', ['Text C.', ['Text D.']]]])
  r.more = h('div', ['Text A.', ['Text B.', ['Text C.', ['Text D.']]]])
  r.more = h('div', null, ['Text A.'], ['Text B.'], ['Text C.'], ['Text D.'])
  r.more = h('div', ['Text A.'], ['Text B.'], ['Text C.'], ['Text D.'])

  for (let r of results)
    t.equal(r, expect)

  t.end()
})

test(`hyperscript should produce valid html when passed attrs and children \
generated by other calls to hyperscript.`, function (t) {
  let h = HyperScript()
  let lipsum = 'Cupcake ipsum dolor sit amet fruitcake tart. Brownie icing jelly-o cake. Jelly cotton candy sweet roll candy cheesecake pudding lollipop jelly dessert.'
  let expect =
`<article
 class="foo bar bar baz"
 style="position:absolute; backgroundColor:#ff0000"
 title="A title attribute">
\t<h1>
\t\tTitle
\t</h1>
\t<p>
\t\t<span>
\t\t\t${lipsum}
\t\t</span>
\t</p>
</article>`

  t.comment(expect)
  let result =
    h('article', fix.props,
      h('h1', 'Title'),
      h('p',
        h('span', lipsum)
      )
    )
  // t.comment(result)
  t.equal(result, expect)

  t.end()
})
